/*
This file is part of eRCaGuy_hello_world: https://github.com/ElectricRCAircraftGuy/eRCaGuy_hello_world

GS
16 Apr. 2022

Learn how to auto-generate unique variable names with the line number in them by using macros.

Ex: `uint64_t MAKE_UNIQUE_VARIABLE_NAME(counter) = 0;` would produce `uint64_t counter_7 = 0` if
this is on line 7!

STATUS: works!

To compile and run (assuming you've already `cd`ed into this dir):
```bash
# Why `-std=gnu17` vs `-std=c17`, and `-std=gnu++17` vs `-std=c++17`?
# See: [my answer]: https://stackoverflow.com/a/71801111/4561887

# 1. In C:
gcc -Wall -Wextra -Werror -O3 -std=gnu17 macro_make_unique_variable_name_with_line_number.c -o bin/a -lm && bin/a

# 2. In C++
g++ -Wall -Wextra -Werror -O3 -std=gnu++17 macro_make_unique_variable_name_with_line_number.c -o bin/a && bin/a
```

References:
1. *****+ [EXTREMELY USEFUL!] Create an identifier at compile time that has the line
   number as part of it: https://stackoverflow.com/a/35922379/4561887
1. Creating C macro with ## and __LINE__ (token concatenation with positioning macro):
   https://stackoverflow.com/a/1597129/4561887

*/

#include <stdbool.h> // For `true` (`1`) and `false` (`0`) macros in C
#include <stdint.h>  // For `uint8_t`, `int8_t`, etc.
#include <stdio.h>   // For `printf()`

// See: https://stackoverflow.com/a/35922379/4561887
#define CONCAT_(prefix, suffix) prefix##suffix
/// Concatenate `prefix, suffix` into `prefixsuffix`
#define CONCAT(prefix, suffix) CONCAT_(prefix, suffix)
/// Make a unique variable name containing the line number at the end of the name. Ex:
/// `uint64_t MAKE_UNIQUE_VARIABLE_NAME(counter) = 0;` would produce `uint64_t counter_7 = 0` if
/// the call is on line 7!
#define MAKE_UNIQUE_VARIABLE_NAME(prefix) CONCAT(prefix##_, __LINE__)


// int main(int argc, char *argv[])  // alternative prototype
int main()
{
    printf("Autogenerate unique variable names containing the line number in them.\n\n");

    uint64_t MAKE_UNIQUE_VARIABLE_NAME(counter) = 0;  // `uint64_t counter_53 = 0;
    uint64_t MAKE_UNIQUE_VARIABLE_NAME(counter) = 0;  // `uint64_t counter_54 = 0;
    uint64_t MAKE_UNIQUE_VARIABLE_NAME(counter) = 0;  // `uint64_t counter_55 = 0;

    // Uncomment this to suppress the errors.
    // (void)counter_53;
    // (void)counter_54;
    // (void)counter_55;

    return 0;
}

/*
SAMPLE OUTPUT:

In C:

Notice that the errors reveal the autogenerated variable names!:

    macro_make_unique_variable_name_with_line_number.c:55:40: error: unused variable ‘counter_55’ [-Werror=unused-variable]
    macro_make_unique_variable_name_with_line_number.c:54:40: error: unused variable ‘counter_54’ [-Werror=unused-variable]
    macro_make_unique_variable_name_with_line_number.c:53:40: error: unused variable ‘counter_53’ [-Werror=unused-variable]

Full output:


    eRCaGuy_hello_world/c$ gcc -Wall -Wextra -Werror -O3 -std=gnu17 macro_make_unique_variable_name_with_line_number.c -o bin/a -lm && bin/a
    macro_make_unique_variable_name_with_line_number.c: In function ‘main’:
    macro_make_unique_variable_name_with_line_number.c:55:40: error: unused variable ‘counter_55’ [-Werror=unused-variable]
       55 |     uint64_t MAKE_UNIQUE_VARIABLE_NAME(counter) = 0;  // `uint64_t counter_55 = 0;
          |                                        ^~~~~~~
    macro_make_unique_variable_name_with_line_number.c:39:33: note: in definition of macro ‘CONCAT_’
       39 | #define CONCAT_(prefix, suffix) prefix##suffix
          |                                 ^~~~~~
    macro_make_unique_variable_name_with_line_number.c:45:43: note: in expansion of macro ‘CONCAT’
       45 | #define MAKE_UNIQUE_VARIABLE_NAME(prefix) CONCAT(prefix##_, __LINE__)
          |                                           ^~~~~~
    macro_make_unique_variable_name_with_line_number.c:55:14: note: in expansion of macro ‘MAKE_UNIQUE_VARIABLE_NAME’
       55 |     uint64_t MAKE_UNIQUE_VARIABLE_NAME(counter) = 0;  // `uint64_t counter_55 = 0;
          |              ^~~~~~~~~~~~~~~~~~~~~~~~~
    macro_make_unique_variable_name_with_line_number.c:54:40: error: unused variable ‘counter_54’ [-Werror=unused-variable]
       54 |     uint64_t MAKE_UNIQUE_VARIABLE_NAME(counter) = 0;  // `uint64_t counter_54 = 0;
          |                                        ^~~~~~~
    macro_make_unique_variable_name_with_line_number.c:39:33: note: in definition of macro ‘CONCAT_’
       39 | #define CONCAT_(prefix, suffix) prefix##suffix
          |                                 ^~~~~~
    macro_make_unique_variable_name_with_line_number.c:45:43: note: in expansion of macro ‘CONCAT’
       45 | #define MAKE_UNIQUE_VARIABLE_NAME(prefix) CONCAT(prefix##_, __LINE__)
          |                                           ^~~~~~
    macro_make_unique_variable_name_with_line_number.c:54:14: note: in expansion of macro ‘MAKE_UNIQUE_VARIABLE_NAME’
       54 |     uint64_t MAKE_UNIQUE_VARIABLE_NAME(counter) = 0;  // `uint64_t counter_54 = 0;
          |              ^~~~~~~~~~~~~~~~~~~~~~~~~
    macro_make_unique_variable_name_with_line_number.c:53:40: error: unused variable ‘counter_53’ [-Werror=unused-variable]
       53 |     uint64_t MAKE_UNIQUE_VARIABLE_NAME(counter) = 0;  // `uint64_t counter_53 = 0;
          |                                        ^~~~~~~
    macro_make_unique_variable_name_with_line_number.c:39:33: note: in definition of macro ‘CONCAT_’
       39 | #define CONCAT_(prefix, suffix) prefix##suffix
          |                                 ^~~~~~
    macro_make_unique_variable_name_with_line_number.c:45:43: note: in expansion of macro ‘CONCAT’
       45 | #define MAKE_UNIQUE_VARIABLE_NAME(prefix) CONCAT(prefix##_, __LINE__)
          |                                           ^~~~~~
    macro_make_unique_variable_name_with_line_number.c:53:14: note: in expansion of macro ‘MAKE_UNIQUE_VARIABLE_NAME’
       53 |     uint64_t MAKE_UNIQUE_VARIABLE_NAME(counter) = 0;  // `uint64_t counter_53 = 0;
          |              ^~~~~~~~~~~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors



OR, in C++:

(very similar to the output in C)


*/
