# This is a Python program written (autogenerated) by and called by the C or C++ program
# "system_call_python.c". Run the C or C++ program to re-generate & call this Python program.
imp = "import os"
exec(imp)
os.system("ping 127.0.0.1")

