#!/usr/bin/python3

"""
This file is part of eRCaGuy_hello_world: https://github.com/ElectricRCAircraftGuy/eRCaGuy_hello_world

Gabriel Staples
Jan. 2021

Demonstrate how to do basic auto-generation of C or C++ code or headers using Python!

To run this script:
    ./autogenerate_c_or_cpp_code.py

...then examine the contents of "autogenerated/myheader.h", which this script just auto-generated!

References:
1. https://stackoverflow.com/questions/10985603/multi-line-string-with-arguments-how-to-declare/64437283#64437283
1. https://stackoverflow.com/questions/5466451/how-can-i-print-literal-curly-brace-characters-in-a-string-and-also-use-format
1. [my code] https://github.com/ElectricRCAircraftGuy/eRCaGuy_hello_world/blob/master/python/yaml_import/import_yaml_test.py


To produce this:
```
struct myStruct {
    int i1;
    float f1;
};
```

do this, for example...
"""

import textwrap


structs_dict = {
    "struct_name": "myStruct",
    "type1": "int",
    "name1": "i1",
    "type2": "float",
    "name2": "f1",
    }

f = open("autogenerated/myheader.h", "w")
f.write(textwrap.dedent('''\
    // This file is autogenerated by Python script "autogenerate_c_or_cpp_code.py"

    #pragma once

    struct {} {{
        {} {};
        {} {};
    }};
    ''').format(
        structs_dict["struct_name"],
        structs_dict["type1"],
        structs_dict["name1"],
        structs_dict["type2"],
        structs_dict["name2"],
        ))
f.close()


"""
After running this script, see the output in "autogenerated/myheader.h"!

"""
