# This file is part of eRCaGuy_hello_world: https://github.com/ElectricRCAircraftGuy/eRCaGuy_hello_world
#
# GS
# Aug. 2026
#
# Generate a header file containing the git commit hash, so that we can access it in C or C++ code
# at run time.
#
# Example usage from a top-level CMakeLists.txt file:
# ```cmake
# include("${CMAKE_SOURCE_DIR}/cmake/git_commit_hash.cmake")
#
# add_executable(my_app
#   main.cpp
# )
# target_link_libraries(my_app
#   PRIVATE
#   git-commit-hash-header-lib
# )
# ```
#
# Example usage in C or C++ code:
# ```cpp
# #include "autogenerated/git_commit_hash.hpp"
# #include <stdio.h>
#
# printf("Git commit hash: " GIT_COMMIT_HASH);
# ```

include("${CMAKE_CURRENT_LIST_DIR}/ansi_colors.cmake") # for `message_yellow()`

set(GIT_COMMIT_HASH_HEADER_DIR "${CMAKE_CURRENT_BINARY_DIR}/autogenerated")
set(GIT_COMMIT_HASH_HEADER_FILE "${GIT_COMMIT_HASH_HEADER_DIR}/git_commit_hash.hpp")

execute_process(
    COMMAND bash -lc ". \"${CMAKE_CURRENT_LIST_DIR}/../bash/git_get_short_hash.sh\"; git_get_short_hash"
    # Ensure we run the `git_get_short_hash` command in the root of the source tree where the repo
    # is.
    WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
    OUTPUT_VARIABLE GIT_COMMIT_HASH_VALUE
    OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE GIT_COMMIT_HASH_RESULT
)

if(NOT GIT_COMMIT_HASH_RESULT EQUAL 0)
    message(FATAL_ERROR "Failed to get git commit hash from 'git_get_short_hash'")
endif()

cmake_path(RELATIVE_PATH CMAKE_CURRENT_LIST_FILE
    BASE_DIRECTORY "${CMAKE_SOURCE_DIR}"
    OUTPUT_VARIABLE CMAKE_CURRENT_LIST_FILE_RELATIVE
)

file(MAKE_DIRECTORY "${GIT_COMMIT_HASH_HEADER_DIR}")
string(CONCAT GIT_COMMIT_HASH_HEADER_CONTENT
    "// This file is autogenerated by CMake file "
    "\"${CMAKE_CURRENT_LIST_FILE_RELATIVE}\".\n"
    "// Do not edit manually.\n"
    "\n"
    "#pragma once\n\n"
    "#define GIT_COMMIT_HASH \"${GIT_COMMIT_HASH_VALUE}\"\n"
)

# Print a message whenever the git commit hash changes and is regenerated.
string(SHA256 GIT_COMMIT_HASH_HEADER_CONTENT_SHA256 "${GIT_COMMIT_HASH_HEADER_CONTENT}")
set(GIT_COMMIT_HASH_HEADER_NEEDS_UPDATE TRUE)
if(EXISTS "${GIT_COMMIT_HASH_HEADER_FILE}")
    file(SHA256 "${GIT_COMMIT_HASH_HEADER_FILE}" GIT_COMMIT_HASH_HEADER_FILE_SHA256)
    if(GIT_COMMIT_HASH_HEADER_FILE_SHA256 STREQUAL GIT_COMMIT_HASH_HEADER_CONTENT_SHA256)
        set(GIT_COMMIT_HASH_HEADER_NEEDS_UPDATE FALSE)
    endif()
endif()
if(GIT_COMMIT_HASH_HEADER_NEEDS_UPDATE)
    message_yellow(
        STATUS
        "Regenerating git commit hash (${GIT_COMMIT_HASH_VALUE}) "
        "header: ${GIT_COMMIT_HASH_HEADER_FILE}"
    )
else()
    message(
        STATUS
        "Git commit hash (${GIT_COMMIT_HASH_VALUE}) header is already up to date: "
        "${GIT_COMMIT_HASH_HEADER_FILE}"
    )
endif()

# NB: Unlike `file(WRITE)`, `file(CONFIGURE)` only updates the output file when the contents change.
# - This prevents rebuilds when the git commit hash hasn't changed, which is important for build
#   performance.
file(CONFIGURE
    OUTPUT "${GIT_COMMIT_HASH_HEADER_FILE}"
    CONTENT "${GIT_COMMIT_HASH_HEADER_CONTENT}"
    @ONLY  # Don't replace variables in the content that are not explicitly marked with @...@.
    NEWLINE_STYLE UNIX
)

# Allow access to the git commit hash header file from C++ code by adding the directory to the
# include path via a small interface library that consumers can link against.
if(NOT TARGET git-commit-hash-header-lib)
    add_library(git-commit-hash-header-lib INTERFACE)

    target_include_directories(git-commit-hash-header-lib
        INTERFACE
        # Expected C or C++ include path: `#include "autogenerated/git_commit_hash.hpp"`
        "${CMAKE_CURRENT_BINARY_DIR}"
    )
endif()
